title: About Me!
author: jmashek
email: test@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Just learning, all the time.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
